### Create
POST http://localhost:5094/notes
Content-Type: application/json

{
  "title": "Blue Note",
  "text": "Hello NoSQL"
}

### List
GET http://localhost:5094/notes?pageSize=5

### Delete (paste an Id)
DELETE http://localhost:5094/notes/{{0d7e0704-5417-462e-a80f-3fdec9a3c8f2}}